apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: grafana-ingress
  namespace: default
spec:
  entryPoints:
    - custom-tcp
  routes:
  - match: Host(`*`)
    kind: Rule
    services:
    - name: grafana
      port: 3000
